name: base

on:
  push:
    branches:
      - 'dev'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: | 
          npm install -g pnpm
          pnpm install
          
      
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Build project
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test project
        run: npm run test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Authenticate with GitHub
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Configure CI Git User
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name GitHubActions

      - name: Version and publish
        run: echo "This step is building yet, please wait!"
        # npm config set //npm.pkg.github.com/_authToken "${{ secrets.GH_TOKEN }}"
        # cd packages/
        # npx lerna version --conventional-commits --no-push
        # npx lerna publish from-git --access private --dist-tag dev --registry https://npm.pkg.github.com
