name: base

on:
  push:
    branches:
      - 'dev'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: | 
          pnpm install
          pnpm install -d rollup
          
      
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - name: building
        run: pnpm run build

      - name: Handle failure
        if: failure()
        run: echo "Por favor, revisa y corrige los errores."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - name: Test project
        run: pnpm run test
        continue-on-error: false
      
      - name: Handle failure
        if: failure()
        run: echo "Por favor, revisa y corrige los errores."

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Authenticate with GitHub
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Configure CI Git User
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name GitHubActions

      - name: Version and publish
        run: echo "This step is building yet, please wait!"
        # npm config set //npm.pkg.github.com/_authToken "${{ secrets.GH_TOKEN }}"
        # cd packages/
        # npx lerna version --conventional-commits --no-push
        # npx lerna publish from-git --access private --dist-tag dev --registry https://npm.pkg.github.com
